<?php

use Drupal\node\Entity\NodeType;
use Drupal\Core\EntityInterface;
use Drupal\Core\Entity\EntityStorageException;
use Drupal\Core\Url;
use Drupal\views\Entity\View;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;
use Drupal\views\ViewEntityInterface;

/**
 * Implements hook_theme
 */
function std_theme($existing, $type, $theme, $path)
{
    return [
        'list-page' => [
            'variables' => array(
                'items' => array(
                    'offset' => '',
                    'first' => '',
                    'last' => '',
                    'previous' => '',
                    'next' => '',
                    'links' => array(),
                    'title' => ''
                )
            )
        ],
    ];
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function std_preprocess_block(&$variables) {
  // Add the rep/rep_js_css library.
  $attachments['#attached']['library'][] = 'rep/rep_js_css';
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function std_menu_links_discovered_alter(&$links) {

  //\Drupal::logger('std_notices')->notice('menu_links_discovered_alter function called.');

  $preferred_process = \Drupal::config('rep.settings')->get('preferred_process');

  if (isset($links['std.manage_process'])) {
    $links['std.manage_process']['title'] = 'Manage ' . $preferred_process;
    $links['std.manage_process']['weight'] = 22;
  }
  if (isset($links['std.manage_processstems'])) {
    $links['std.manage_processstems']['title'] = 'Manage ' . $preferred_process . ' Stems';
    $links['std.manage_processstems']['weight'] = 23;
  }
}
