name: Run Selenium Tests

on:
  push:
    branches:
      - workflow
      - stable_version
jobs:
  run-selenium-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_131.0.6778.69-1_amd64.deb
          sudo apt install -y --allow-downgrades ./google-chrome-stable_131.0.6778.69-1_amd64.deb
        
      - name: Download and Install ChromeDriver
        run: |
          DRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.69/linux64/chromedriver-linux64.zip"
    
          curl -L -o chromedriver.zip "$DRIVER_URL"
          
          mkdir -p $HOME/chromedriver
          unzip -o chromedriver.zip -d $HOME/chromedriver/
          rm chromedriver.zip

          mv $HOME/chromedriver/chromedriver-linux64/chromedriver $HOME/chromedriver/chromedriver
          chmod +x $HOME/chromedriver/chromedriver

          echo "$HOME/chromedriver" >> $GITHUB_PATH
          
      - name: Download Selenium standalone jar
        run: |
          curl -L -o selenium-server.jar https://repo1.maven.org/maven2/org/seleniumhq/selenium/selenium-server/latest/selenium-server-latest.jar

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99

      - name: Compile BaseTest.java
        run: |
          javac -cp ".:tests/selenium-java-4.26.0/selenium-java-4.26.0.jar:tests/selenium-java-4.26.0/libs/*:tests/junit-platform-console-standalone-1.8.2.jar" tests/BaseTest.java

      - name: Compile SDD.java
        run: |
          javac -cp ".:tests/selenium-java-4.26.0/selenium-java-4.26.0.jar:tests/selenium-java-4.26.0/libs/*:tests/junit-platform-console-standalone-1.8.2.jar" tests/SDD.java

      - name: Compile DSG.java
        run: |
          javac -cp ".:tests/selenium-java-4.26.0/selenium-java-4.26.0.jar:tests/selenium-java-4.26.0/libs/*:tests/junit-platform-console-standalone-1.8.2.jar" tests/DSG.java

      - name: Wait for hascogui to be ready
        run: |
          until curl -s http://localhost:8081/ > /dev/null; do
            echo "Waiting for hascogui environment to start..."
            sleep 5
          done

      - name: Run SDD Test
        run: |
          java -Dfile="/metadata/NHANES-2017-2018/SDDs/SDD-NHANES-BMX.xlsx" -Dcard-name="NHANES BMX" -Dsdd-title="NHANES-BMX" -cp ".:tests/junit-platform-console-standalone-1.8.2.jar:tests/selenium-java-4.26.0/selenium-java-4.26.0.jar:tests/selenium-java-4.26.0/libs/*:tests" org.junit.platform.console.ConsoleLauncher --select-class "tests.SDD"

      - name: Run DSG Test
        run: |
          java -Dfile="/metadata/NHANES-2017-2018/DSGs/DSG-NHANES-2017-2018-100.xlsx" -Dcard-name="NHANES 2017-2018" -Ddsg-title="NHANES-2017-2018" -cp ".:tests/junit-platform-console-standalone-1.8.2.jar:tests/selenium-java-4.26.0/selenium-java-4.26.0.jar:tests/selenium-java-4.26.0/libs/*:tests" org.junit.platform.console.ConsoleLauncher --select-class "tests.DSG"

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            const message = `❌ The tests have failed! @${prAuthor}, please check the logs and fix the problems before merging.`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message
            });
      - name: Notify via Slack on failure
        if: failure()
        run: |
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"❌ The tests for the PR #${{ github.event.pull_request.number }} have failed. Author: @${{ github.event.pull_request.user.login }}. Check the details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ The tests for the PR #${{ github.event.pull_request.number }} have passed! Author: @${{ github.event.pull_request.user.login }}. Check the details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}